import type { TheaterCapability } from '@/lib/voyage';

import { imaxGuideCatalog } from './imaxguide';

// Curated launch catalog. Capability and screening confirmation are separate:
// a venue can own 15/70 equipment without a confirmed Odyssey engagement.
const curatedTheaterCatalog: TheaterCapability[] = [
  {
    id: 'amc-lincoln-square-13',
    name: 'AMC Lincoln Square 13',
    city: 'New York',
    region: 'NY',
    country: 'US',
    latitude: 40.7751,
    longitude: -73.9822,
    formats: ['IMAX 15/70mm', 'IMAX with Laser'],
    projector: '15/70 film + Dual GT Laser',
    aspectRatio: 'Up to 1.43:1',
    has1570: true,
    hasGtLaser: true,
    worthVoyage: true,
    screeningStatus: 'unknown',
    verifiedAt: '2026-07-01',
    sourceUrl: 'https://www.imax.com/theatre/amc-lincoln-square-13-imax',
    confidence: 'high',
  },
  {
    id: 'amc-metreon-16',
    name: 'AMC Metreon 16',
    city: 'San Francisco',
    region: 'CA',
    country: 'US',
    latitude: 37.7846,
    longitude: -122.4032,
    formats: ['IMAX 15/70mm', 'IMAX with Laser'],
    projector: '15/70 film + Dual GT Laser',
    aspectRatio: 'Up to 1.43:1',
    has1570: true,
    hasGtLaser: true,
    worthVoyage: true,
    screeningStatus: 'unknown',
    verifiedAt: '2026-07-01',
    sourceUrl: 'https://www.imax.com/theatre/amc-metreon-16-imax',
    confidence: 'high',
  },
  {
    id: 'universal-citywalk-hollywood',
    name: 'Universal Cinema AMC at CityWalk Hollywood',
    city: 'Universal City',
    region: 'CA',
    country: 'US',
    latitude: 34.1378,
    longitude: -118.3534,
    formats: ['IMAX 15/70mm', 'IMAX with Laser'],
    projector: '15/70 film + Dual GT Laser',
    aspectRatio: 'Up to 1.43:1',
    has1570: true,
    hasGtLaser: true,
    worthVoyage: true,
    screeningStatus: 'unknown',
    verifiedAt: '2026-07-01',
    sourceUrl:
      'https://www.imax.com/theatre/universal-cinema-amc-at-citywalk-hollywood-imax',
    confidence: 'high',
  },
  {
    id: 'regal-irvine-spectrum',
    name: 'Regal Irvine Spectrum',
    city: 'Irvine',
    region: 'CA',
    country: 'US',
    latitude: 33.6501,
    longitude: -117.7437,
    formats: ['IMAX 15/70mm', 'IMAX with Laser'],
    projector: '15/70 film + Single Laser',
    aspectRatio: 'Up to 1.43:1 on film',
    has1570: true,
    hasGtLaser: false,
    worthVoyage: true,
    screeningStatus: 'unknown',
    verifiedAt: '2026-07-01',
    sourceUrl: 'https://www.imax.com/theatre/regal-irvine-spectrum-imax',
    confidence: 'high',
  },
  {
    id: 'regal-ontario-palace',
    name: 'Regal Edwards Ontario Palace',
    city: 'Ontario',
    region: 'CA',
    country: 'US',
    latitude: 34.0709,
    longitude: -117.5522,
    formats: ['IMAX 15/70mm', 'IMAX Digital'],
    projector: '15/70 film + Xenon digital',
    aspectRatio: 'Up to 1.43:1 on film',
    has1570: true,
    hasGtLaser: false,
    worthVoyage: true,
    screeningStatus: 'unknown',
    verifiedAt: '2026-07-01',
    sourceUrl: 'https://www.imax.com/theatre/regal-edwards-ontario-palace-imax',
    confidence: 'high',
  },
  {
    id: 'harkins-arizona-mills',
    name: 'Harkins Arizona Mills 18',
    city: 'Tempe',
    region: 'AZ',
    country: 'US',
    latitude: 33.3832,
    longitude: -111.9644,
    formats: ['IMAX 15/70mm', 'IMAX Digital'],
    projector: '15/70 film + Xenon digital',
    aspectRatio: 'Up to 1.43:1 on film',
    has1570: true,
    hasGtLaser: false,
    worthVoyage: true,
    screeningStatus: 'unknown',
    verifiedAt: '2026-07-01',
    sourceUrl: 'https://www.imax.com/theatre/harkins-arizona-mills-18-imax',
    confidence: 'high',
  },
  {
    id: 'cinemark-dallas-17',
    name: 'Cinemark Dallas XD and IMAX',
    city: 'Dallas',
    region: 'TX',
    country: 'US',
    latitude: 32.9127,
    longitude: -96.7701,
    formats: ['IMAX 15/70mm', 'IMAX Digital'],
    projector: '15/70 film + Xenon digital',
    aspectRatio: 'Up to 1.43:1 on film',
    has1570: true,
    hasGtLaser: false,
    worthVoyage: true,
    screeningStatus: 'unknown',
    verifiedAt: '2026-07-01',
    sourceUrl: 'https://www.imax.com/theatre/cinemark-dallas-imax',
    confidence: 'high',
  },
  {
    id: 'amc-rivercenter-11',
    name: 'AMC Rivercenter 11',
    city: 'San Antonio',
    region: 'TX',
    country: 'US',
    latitude: 29.4235,
    longitude: -98.484,
    formats: ['IMAX 15/70mm', 'IMAX Digital'],
    projector: '15/70 film + Xenon digital',
    aspectRatio: 'Up to 1.43:1 on film',
    has1570: true,
    hasGtLaser: false,
    worthVoyage: true,
    screeningStatus: 'unknown',
    verifiedAt: '2026-07-01',
    sourceUrl: 'https://www.imax.com/theatre/amc-rivercenter-11-imax',
    confidence: 'medium',
  },
  {
    id: 'bullock-imax',
    name: 'Bullock Museum IMAX Theatre',
    city: 'Austin',
    region: 'TX',
    country: 'US',
    latitude: 30.2804,
    longitude: -97.739,
    formats: ['IMAX with Laser'],
    projector: 'Dual GT Laser',
    aspectRatio: 'Up to 1.43:1',
    has1570: false,
    hasGtLaser: true,
    worthVoyage: true,
    screeningStatus: 'unknown',
    verifiedAt: '2026-07-01',
    sourceUrl: 'https://www.thestoryoftexas.com/visit/calendar/imax',
    confidence: 'high',
  },
  {
    id: 'indiana-state-museum',
    name: 'IMAX Theater at the Indiana State Museum',
    city: 'Indianapolis',
    region: 'IN',
    country: 'US',
    latitude: 39.7686,
    longitude: -86.1694,
    formats: ['IMAX 15/70mm', 'IMAX Digital'],
    projector: '15/70 film + digital',
    aspectRatio: 'Up to 1.43:1 on film',
    has1570: true,
    hasGtLaser: false,
    worthVoyage: true,
    screeningStatus: 'unknown',
    verifiedAt: '2026-07-01',
    sourceUrl: 'https://www.imaxindy.com/',
    confidence: 'high',
  },
  {
    id: 'celebration-grand-rapids',
    name: 'Celebration Cinema Grand Rapids North',
    city: 'Grand Rapids',
    region: 'MI',
    country: 'US',
    latitude: 43.0243,
    longitude: -85.6746,
    formats: ['IMAX 15/70mm', 'IMAX Digital'],
    projector: '15/70 film + digital',
    aspectRatio: 'Up to 1.43:1 on film',
    has1570: true,
    hasGtLaser: false,
    worthVoyage: true,
    screeningStatus: 'unknown',
    verifiedAt: '2026-07-01',
    sourceUrl:
      'https://www.imax.com/theatre/celebration-cinema-grand-rapids-north-imax',
    confidence: 'medium',
  },
  {
    id: 'regal-opry-mills',
    name: 'Regal Opry Mills',
    city: 'Nashville',
    region: 'TN',
    country: 'US',
    latitude: 36.203,
    longitude: -86.6935,
    formats: ['IMAX 15/70mm', 'IMAX Digital'],
    projector: '15/70 film + digital',
    aspectRatio: 'Up to 1.43:1 on film',
    has1570: true,
    hasGtLaser: false,
    worthVoyage: true,
    screeningStatus: 'unknown',
    verifiedAt: '2026-07-01',
    sourceUrl: 'https://www.imax.com/theatre/regal-opry-mills-imax',
    confidence: 'high',
  },
  {
    id: 'regal-mall-of-georgia',
    name: 'Regal Mall of Georgia',
    city: 'Buford',
    region: 'GA',
    country: 'US',
    latitude: 34.064,
    longitude: -83.9844,
    formats: ['IMAX 15/70mm', 'IMAX with Laser'],
    projector: '15/70 film + laser',
    aspectRatio: 'Up to 1.43:1 on film',
    has1570: true,
    hasGtLaser: false,
    worthVoyage: true,
    screeningStatus: 'unknown',
    verifiedAt: '2026-07-01',
    sourceUrl: 'https://www.imax.com/theatre/regal-mall-of-georgia-imax',
    confidence: 'high',
  },
  {
    id: 'autonation-imax',
    name: 'AutoNation IMAX Theater',
    city: 'Fort Lauderdale',
    region: 'FL',
    country: 'US',
    latitude: 26.1199,
    longitude: -80.1446,
    formats: ['IMAX 15/70mm', 'IMAX with Laser'],
    projector: '15/70 film + Dual GT Laser',
    aspectRatio: 'Up to 1.43:1',
    has1570: true,
    hasGtLaser: true,
    worthVoyage: true,
    screeningStatus: 'unknown',
    verifiedAt: '2026-07-01',
    sourceUrl: 'https://mods.org/autonation-imax-theater/',
    confidence: 'high',
  },
  {
    id: 'airbus-imax',
    name: 'Airbus IMAX Theater',
    city: 'Chantilly',
    region: 'VA',
    country: 'US',
    latitude: 38.9114,
    longitude: -77.4442,
    formats: ['IMAX with Laser'],
    projector: 'Dual GT Laser',
    aspectRatio: 'Up to 1.43:1',
    has1570: false,
    hasGtLaser: true,
    worthVoyage: true,
    screeningStatus: 'unknown',
    verifiedAt: '2026-07-01',
    sourceUrl: 'https://airandspace.si.edu/visit/imax-theaters',
    confidence: 'high',
  },
  {
    id: 'jordans-reading',
    name: "Jordan's Furniture IMAX Reading",
    city: 'Reading',
    region: 'MA',
    country: 'US',
    latitude: 42.5156,
    longitude: -71.1006,
    formats: ['IMAX with Laser'],
    projector: 'Dual GT Laser',
    aspectRatio: 'Up to 1.43:1',
    has1570: false,
    hasGtLaser: true,
    worthVoyage: true,
    screeningStatus: 'unknown',
    verifiedAt: '2026-07-01',
    sourceUrl: 'https://www.jordans.com/imax',
    confidence: 'high',
  },
  {
    id: 'providence-place',
    name: 'Providence Place Cinemas 16',
    city: 'Providence',
    region: 'RI',
    country: 'US',
    latitude: 41.8289,
    longitude: -71.4168,
    formats: ['IMAX 15/70mm', 'IMAX Digital'],
    projector: '15/70 film + digital',
    aspectRatio: 'Up to 1.43:1 on film',
    has1570: true,
    hasGtLaser: false,
    worthVoyage: true,
    screeningStatus: 'unknown',
    verifiedAt: '2026-07-01',
    sourceUrl: 'https://www.imax.com/theatre/providence-place-cinemas-imax',
    confidence: 'medium',
  },
  {
    id: 'tennessee-aquarium',
    name: 'Tennessee Aquarium IMAX 3D Theater',
    city: 'Chattanooga',
    region: 'TN',
    country: 'US',
    latitude: 35.0557,
    longitude: -85.3108,
    formats: ['IMAX with Laser'],
    projector: 'Dual GT Laser',
    aspectRatio: 'Up to 1.43:1',
    has1570: false,
    hasGtLaser: true,
    worthVoyage: true,
    screeningStatus: 'unknown',
    verifiedAt: '2026-07-01',
    sourceUrl: 'https://tnaqua.org/imax/',
    confidence: 'high',
  },
  {
    id: 'scotiabank-toronto',
    name: 'Scotiabank Theatre Toronto',
    city: 'Toronto',
    region: 'ON',
    country: 'CA',
    latitude: 43.6489,
    longitude: -79.3912,
    formats: ['IMAX 15/70mm', 'IMAX with Laser'],
    projector: '15/70 film + Dual GT Laser',
    aspectRatio: 'Up to 1.43:1',
    has1570: true,
    hasGtLaser: true,
    worthVoyage: true,
    screeningStatus: 'unknown',
    verifiedAt: '2026-07-01',
    sourceUrl: 'https://www.cineplex.com/theatre/scotiabank-theatre-toronto',
    confidence: 'high',
  },
  {
    id: 'cineplex-vaughan',
    name: 'Cineplex Cinemas Vaughan',
    city: 'Vaughan',
    region: 'ON',
    country: 'CA',
    latitude: 43.7925,
    longitude: -79.5277,
    formats: ['IMAX 15/70mm', 'IMAX Digital'],
    projector: '15/70 film + digital',
    aspectRatio: 'Up to 1.43:1 on film',
    has1570: true,
    hasGtLaser: false,
    worthVoyage: true,
    screeningStatus: 'unknown',
    verifiedAt: '2026-07-01',
    sourceUrl: 'https://www.cineplex.com/theatre/cineplex-cinemas-vaughan',
    confidence: 'high',
  },
  {
    id: 'cineplex-mississauga',
    name: 'Cineplex Cinemas Mississauga',
    city: 'Mississauga',
    region: 'ON',
    country: 'CA',
    latitude: 43.5931,
    longitude: -79.6428,
    formats: ['IMAX 15/70mm', 'IMAX Digital'],
    projector: '15/70 film + digital',
    aspectRatio: 'Up to 1.43:1 on film',
    has1570: true,
    hasGtLaser: false,
    worthVoyage: true,
    screeningStatus: 'unknown',
    verifiedAt: '2026-07-01',
    sourceUrl: 'https://www.cineplex.com/theatre/cineplex-cinemas-mississauga',
    confidence: 'medium',
  },
  {
    id: 'cineplex-langley',
    name: 'Cineplex Cinemas Langley',
    city: 'Langley',
    region: 'BC',
    country: 'CA',
    latitude: 49.1133,
    longitude: -122.6741,
    formats: ['IMAX 15/70mm', 'IMAX Digital'],
    projector: '15/70 film + digital',
    aspectRatio: 'Up to 1.43:1 on film',
    has1570: true,
    hasGtLaser: false,
    worthVoyage: true,
    screeningStatus: 'unknown',
    verifiedAt: '2026-07-01',
    sourceUrl: 'https://www.cineplex.com/theatre/cineplex-cinemas-langley',
    confidence: 'high',
  },
  {
    id: 'imax-victoria',
    name: 'IMAX Victoria',
    city: 'Victoria',
    region: 'BC',
    country: 'CA',
    latitude: 48.4197,
    longitude: -123.368,
    formats: ['IMAX with Laser'],
    projector: 'Dual GT Laser',
    aspectRatio: 'Up to 1.43:1',
    has1570: false,
    hasGtLaser: true,
    worthVoyage: true,
    screeningStatus: 'unknown',
    verifiedAt: '2026-07-01',
    sourceUrl: 'https://imaxvictoria.com/',
    confidence: 'high',
  },
  {
    id: 'scotiabank-chinook',
    name: 'Scotiabank Theatre Chinook',
    city: 'Calgary',
    region: 'AB',
    country: 'CA',
    latitude: 50.997,
    longitude: -114.074,
    formats: ['IMAX 15/70mm', 'IMAX Digital'],
    projector: '15/70 film + digital',
    aspectRatio: 'Up to 1.43:1 on film',
    has1570: true,
    hasGtLaser: false,
    worthVoyage: true,
    screeningStatus: 'unknown',
    verifiedAt: '2026-07-01',
    sourceUrl: 'https://www.cineplex.com/theatre/scotiabank-theatre-chinook',
    confidence: 'high',
  },
  {
    id: 'kramer-imax',
    name: 'Kramer IMAX Theatre',
    city: 'Regina',
    region: 'SK',
    country: 'CA',
    latitude: 50.4452,
    longitude: -104.6067,
    formats: ['IMAX with Laser'],
    projector: 'Dual GT Laser',
    aspectRatio: 'Up to 1.43:1',
    has1570: false,
    hasGtLaser: true,
    worthVoyage: true,
    screeningStatus: 'unknown',
    verifiedAt: '2026-07-01',
    sourceUrl: 'https://www.sasksciencecentre.com/kramer-imax-theatre',
    confidence: 'high',
  },
  {
    id: 'scotiabank-montreal',
    name: 'Cinéma Banque Scotia Montréal',
    city: 'Montreal',
    region: 'QC',
    country: 'CA',
    latitude: 45.4987,
    longitude: -73.5745,
    formats: ['IMAX 15/70mm', 'IMAX Digital'],
    projector: '15/70 film + digital',
    aspectRatio: 'Up to 1.43:1 on film',
    has1570: true,
    hasGtLaser: false,
    worthVoyage: true,
    screeningStatus: 'unknown',
    verifiedAt: '2026-07-01',
    sourceUrl: 'https://www.cineplex.com/theatre/cinema-banque-scotia-montreal',
    confidence: 'medium',
  },
  {
    id: 'amc-boston-common',
    name: 'AMC Boston Common 19',
    city: 'Boston',
    region: 'MA',
    country: 'US',
    latitude: 42.353,
    longitude: -71.064,
    formats: ['IMAX with Laser'],
    projector: 'Commercial Laser',
    aspectRatio: 'Up to 1.90:1',
    has1570: false,
    hasGtLaser: false,
    worthVoyage: false,
    screeningStatus: 'unknown',
    verifiedAt: '2026-07-01',
    sourceUrl: 'https://www.imax.com/theatre/amc-boston-common-19-imax',
    confidence: 'medium',
  },
  {
    id: 'amc-empire-25',
    name: 'AMC Empire 25',
    city: 'New York',
    region: 'NY',
    country: 'US',
    latitude: 40.7567,
    longitude: -73.9885,
    formats: ['IMAX with Laser'],
    projector: 'Commercial Laser',
    aspectRatio: 'Up to 1.90:1',
    has1570: false,
    hasGtLaser: false,
    worthVoyage: false,
    screeningStatus: 'unknown',
    verifiedAt: '2026-07-01',
    sourceUrl: 'https://www.imax.com/theatre/amc-empire-25-imax',
    confidence: 'medium',
  },
  {
    id: 'amc-georgetown-14',
    name: 'AMC Georgetown 14',
    city: 'Washington',
    region: 'DC',
    country: 'US',
    latitude: 38.8977,
    longitude: -77.0734,
    formats: ['IMAX with Laser'],
    projector: 'Commercial Laser',
    aspectRatio: 'Up to 1.90:1',
    has1570: false,
    hasGtLaser: false,
    worthVoyage: false,
    screeningStatus: 'unknown',
    verifiedAt: '2026-07-01',
    sourceUrl: 'https://www.imax.com/theatre/amc-georgetown-14-imax',
    confidence: 'medium',
  },
  {
    id: 'amc-northpark-15',
    name: 'AMC NorthPark 15',
    city: 'Dallas',
    region: 'TX',
    country: 'US',
    latitude: 32.8686,
    longitude: -96.7733,
    formats: ['IMAX with Laser'],
    projector: 'Commercial Laser',
    aspectRatio: 'Up to 1.90:1',
    has1570: false,
    hasGtLaser: false,
    worthVoyage: false,
    screeningStatus: 'unknown',
    verifiedAt: '2026-07-01',
    sourceUrl: 'https://www.imax.com/theatre/amc-northpark-15-imax',
    confidence: 'medium',
  },
  {
    id: 'amc-iconic-16',
    name: 'AMC Burbank 16',
    city: 'Burbank',
    region: 'CA',
    country: 'US',
    latitude: 34.1811,
    longitude: -118.3124,
    formats: ['IMAX with Laser'],
    projector: 'Commercial Laser',
    aspectRatio: 'Up to 1.90:1',
    has1570: false,
    hasGtLaser: false,
    worthVoyage: false,
    screeningStatus: 'unknown',
    verifiedAt: '2026-07-01',
    sourceUrl: 'https://www.imax.com/theatre/amc-burbank-16-imax',
    confidence: 'medium',
  },
  {
    id: 'amc-seattle-10',
    name: 'AMC Pacific Place 11',
    city: 'Seattle',
    region: 'WA',
    country: 'US',
    latitude: 47.6122,
    longitude: -122.3365,
    formats: ['IMAX Digital'],
    projector: 'IMAX digital',
    aspectRatio: 'Up to 1.90:1',
    has1570: false,
    hasGtLaser: false,
    worthVoyage: false,
    screeningStatus: 'unknown',
    verifiedAt: '2026-07-01',
    sourceUrl: 'https://www.imax.com/',
    confidence: 'medium',
  },
  {
    id: 'cineplex-metrotown',
    name: 'Cineplex Cinemas Metropolis',
    city: 'Burnaby',
    region: 'BC',
    country: 'CA',
    latitude: 49.2267,
    longitude: -123.0008,
    formats: ['IMAX Digital'],
    projector: 'IMAX digital',
    aspectRatio: 'Up to 1.90:1',
    has1570: false,
    hasGtLaser: false,
    worthVoyage: false,
    screeningStatus: 'unknown',
    verifiedAt: '2026-07-01',
    sourceUrl: 'https://www.cineplex.com/theatre/cineplex-cinemas-metropolis',
    confidence: 'medium',
  },
];

const replacementIds = new Set([
  'imaxguide-us-reading-sunbrella-imax-3d-theater-reading',
]);

function theaterNameTokens(value: string) {
  return new Set(
    value
      .normalize('NFKD')
      .replace(/[\u0300-\u036f]/g, '')
      .toLowerCase()
      .replace(
        /\b(imax|cinema|cinemas|theater|theatre|at|the|of|and|3d|xd)\b/g,
        ' '
      )
      .replace(/[^a-z0-9]+/g, ' ')
      .trim()
      .split(/\s+/)
      .filter(Boolean)
  );
}

function sameTheater(curated: TheaterCapability, imported: TheaterCapability) {
  if (curated.country !== imported.country) return false;
  const curatedTokens = theaterNameTokens(curated.name);
  const importedTokens = theaterNameTokens(imported.name);
  const overlap = [...curatedTokens].filter((token) =>
    importedTokens.has(token)
  ).length;
  return (
    overlap / Math.max(1, Math.min(curatedTokens.size, importedTokens.size)) >=
    0.75
  );
}

export const theaterCatalog: TheaterCapability[] = [
  ...curatedTheaterCatalog,
  ...imaxGuideCatalog.filter(
    (imported) =>
      !replacementIds.has(imported.id) &&
      !curatedTheaterCatalog.some((curated) => sameTheater(curated, imported))
  ),
].sort(
  (left, right) =>
    left.country.localeCompare(right.country) ||
    left.city.localeCompare(right.city) ||
    left.name.localeCompare(right.name)
);
